# This configuration uses S3 as shared storage between different
# build stages.

# It assums S3 credentials to be set up in the repository settings
# or to be configured as encrypted env vars here.

sudo: false

env:
  global:
    # include $HOME/.local/bin for `aws`
    - AWS_ACCESS_KEY_ID=AKIAXO3CMFTOMQF7SWEE
    - AWS_SECRET_ACCESS_KEY=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
    - AWS_DEFAULT_REGION=us-east-2

before_install:
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/shared
  - aws s3 sync s3://latoken/shared ~/shared

jobs:
  include:
    - stage: setup files
      script: echo one | tee > ~/shared/one
    - stage: setup files
      script: echo two | tee > ~/shared/two
    - stage: use shared files 
      script:
        - cat ~/shared/*

after_success:
  - aws s3 sync ~/shared s3://latoken/shared