sudo: false

env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAXO3CMFTOMQF7SWEE
    - AWS_SECRET_ACCESS_KEY=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
    - AWS_DEFAULT_REGION=us-east-2

before_install:
  # set up awscli packages
  - pip3 install --user awscli
  - mkdir -p ~/shared/lib
  - aws s3 sync s3://latoken/shared/lib ~/shared/lib

jobs:
  include:
    # - stage: Build
    #   os: linux
    #   language: go
    #   go: 1.17.3
    #   script:
    #     - go get -d -v ./...
    #     - go build -o lib/linux-x64/libhub.so -buildmode=c-shared embedded_hub.go
    #     - cp -r lib/linux-x64 ~/shared/lib

    - stage: Build
      os: osx
      language: 
        - go
        - python
      go: 1.17.3
      script:
        - go get -d -v ./...
        - go build -o lib/osx-x64/libhub.dylib -buildmode=c-shared embedded_hub.go
        - cp -r lib/osx-x64 ~/shared/lib
    
    - stage: Build
      os: windows
      language: 
        - go
        - python
      go: 1.17.3
      script:
        - go get -d -v ./...
        - go build -o lib/win-x64/libhub.dll -buildmode=c-shared embedded_hub.go
        - cp -r lib/win-x64 ~/shared/lib

    # - stage: Deploy  
    #   language: minimal 
    #   deploy:
    #     provider: releases
    #     api_key: "$GITHUB_TOKEN"
    #     file_glob: true
    #     file: libhub_.*
    #     skip_cleanup: true
    #     on:
    #       tags: true
    #       all_branches: true
    
    - stage: Nuget_build
      language: csharp
      dotnet: 5.0
      mono: none
      dist: focal
      addons:
        apt:
          packages:
            - dotnet-sdk-3.1
            - nuget
      env:
        global:
          - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
          - DOTNET_CLI_TELEMETRY_OPTOUT=1
      install:
        - dotnet restore Lachain.CommunicationHub.Net
        - dotnet build -c Release Lachain.CommunicationHub.Net
      script:
        - cp -r ~/shared/lib .
        - nuget pack Lachain.CommunicationHub.Native.nuspec
        - cd Lachain.CommunicationHub.Net/
        - dotnet build Lachain.CommunicationHub.Net.sln
        - dotnet pack Lachain.CommunicationHub.Net.csproj

    #   deploy:
    #     provider: releases
    #     api_key: "$GITHUB_TOKEN"
    #     file_glob: true
    #     file: bin/*
    #     skip_cleanup: true
    #     draft: true
    #     on:
    #       tags: true

    # - stage: Dotnet_build 
    #   language: csharp
    #   dotnet: 5.0
    #   mono: none
    #   dist: focal
    #   addons:
    #     apt:
    #       packages:
    #         - dotnet-sdk-3.1
    #         - nuget
    #   env:
    #     global:
    #       - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    #       - DOTNET_CLI_TELEMETRY_OPTOUT=1      
    #   install:
    #     - dotnet restore Lachain.CommunicationHub.Net
    #     - dotnet build -c Release Lachain.CommunicationHub.Net
    #   script:
    #     - cd Lachain.CommunicationHub.Net/
    #     - dotnet build Lachain.CommunicationHub.Net.sln
    #     - dotnet pack Lachain.CommunicationHub.Net.csproj
    #   deploy:
    #     provider: releases
    #     api_key: "$GITHUB_TOKEN"
    #     file_glob: true
    #     file: bin/*
    #     skip_cleanup: true
    #     draft: true
    #     on:
    #       tags: true

after_success:
  - aws s3 sync ~/shared s3://latoken/shared