language: go
install:
  - go build extended_hub.go -o libhub.so
script:
  - go test utils/utils_test.go
  - go test config/config_test.go

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: libhub.so
  skip_cleanup: true
  draft: true
  on:
    tags: true
